# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [24]:
import pandas as pd
import numpy as np

df = pd.read_csv("tic-tac-toe.csv")
display(df.head())
display(df.shape)
display(df.describe())
display(df.dtypes)
display(df.nunique())
display(df.value_counts())


display(df.head())
display(df.shape)

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

(958, 10)

         TL   TM   TR   ML   MM   MR   BL   BM   BR class
count   958  958  958  958  958  958  958  958  958   958
unique    3    3    3    3    3    3    3    3    3     2
top       x    x    x    x    x    x    x    x    x  True
freq    418  378  418  378  458  378  418  378  418   626

TL        str
TM        str
TR        str
ML        str
MM        str
MR        str
BL        str
BM        str
BR        str
class    bool
dtype: object

TL       3
TM       3
TR       3
ML       3
MM       3
MR       3
BL       3
BM       3
BR       3
class    2
dtype: int64

TL  TM  TR  ML  MM  MR  BL  BM  BR  class
x   x   x   x   o   o   x   o   o   True     1
                        o   x   o   True     1
                            o   x   True     1
                            b   b   True     1
                        b   o   b   True     1
                                            ..
o   x   x   x   o   o   o   x   x   False    1
        o   x   x   o   x   o   x   False    1
                o   x   x   o   x   False    1
            o   x   x   x   o   x   False    1
    o   x   x   x   o   o   x   x   False    1
Name: count, Length: 958, dtype: int64

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

(958, 10)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [53]:
# your code here
from sklearn.model_selection import train_test_split
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

predictor = df[df.columns[df.columns != "class"]]
predictor_clean = pd.get_dummies(predictor, drop_first=True)
display(predictor_clean.dtypes)
target = df["class"]

n_cols = predictor_clean.shape[1]

x_train, x_test, y_train, y_test = train_test_split(
    predictor_clean,
    target,
    test_size=0.2,
    random_state=42
)

x_train = x_train.values.astype('float32')
def regression_model():
    model = Sequential()
    model.add(Dense(32, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(3, activation='softmax'))

    # compile model
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model


# build the model
model = regression_model()

TL_o    bool
TL_x    bool
TM_o    bool
TM_x    bool
TR_o    bool
TR_x    bool
ML_o    bool
ML_x    bool
MM_o    bool
MM_x    bool
MR_o    bool
MR_x    bool
BL_o    bool
BL_x    bool
BM_o    bool
BM_x    bool
BR_o    bool
BR_x    bool
dtype: object

c:\Users\ramor\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\keras\src\layers\core\dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [54]:
# your code here

# fit the model
model.fit(x_train, y_train, epochs=100, verbose=2)

y_pred = model.predict(x_test)

display(x_test.head())
y_pred_classes = np.argmax(y_pred, axis=1)
print(y_pred_classes)

Epoch 1/100
24/24 - 1s - 57ms/step - accuracy: 0.6527 - loss: 0.7692
Epoch 2/100
24/24 - 0s - 4ms/step - accuracy: 0.6527 - loss: 0.6826
Epoch 3/100
24/24 - 0s - 4ms/step - accuracy: 0.6593 - loss: 0.6389
Epoch 4/100
24/24 - 0s - 4ms/step - accuracy: 0.6684 - loss: 0.6057
Epoch 5/100
24/24 - 0s - 4ms/step - accuracy: 0.7010 - loss: 0.5753
Epoch 6/100
24/24 - 0s - 4ms/step - accuracy: 0.7285 - loss: 0.5471
Epoch 7/100
24/24 - 0s - 4ms/step - accuracy: 0.7533 - loss: 0.5214
Epoch 8/100
24/24 - 0s - 4ms/step - accuracy: 0.7702 - loss: 0.4970
Epoch 9/100
24/24 - 0s - 4ms/step - accuracy: 0.7833 - loss: 0.4736
Epoch 10/100
24/24 - 0s - 6ms/step - accuracy: 0.7911 - loss: 0.4487
Epoch 11/100
24/24 - 0s - 4ms/step - accuracy: 0.8081 - loss: 0.4227
Epoch 12/100
24/24 - 0s - 7ms/step - accuracy: 0.8303 - loss: 0.3944
Epoch 13/100
24/24 - 0s - 4ms/step - accuracy: 0.8525 - loss: 0.3641
Epoch 14/100
24/24 - 0s - 4ms/step - accuracy: 0.8890 - loss: 0.3306
Epoch 15/100
24/24 - 0s - 4ms/step - accuracy: 0.9230 - loss: 0.2944
Epoch 16/100
24/24 - 0s - 5ms/step - accuracy: 0.9452 - loss: 0.2580
Epoch 17/100
24/24 - 0s - 5ms/step - accuracy: 0.9661 - loss: 0.2224
Epoch 18/100
24/24 - 0s - 5ms/step - accuracy: 0.9752 - loss: 0.1884
Epoch 19/100
24/24 - 0s - 7ms/step - accuracy: 0.9830 - loss: 0.1582
Epoch 20/100
24/24 - 0s - 4ms/step - accuracy: 0.9830 - loss: 0.1330
Epoch 21/100
24/24 - 0s - 4ms/step - accuracy: 0.9856 - loss: 0.1124
Epoch 22/100
24/24 - 0s - 4ms/step - accuracy: 0.9856 - loss: 0.0966
Epoch 23/100
24/24 - 0s - 4ms/step - accuracy: 0.9869 - loss: 0.0842
Epoch 24/100
24/24 - 0s - 4ms/step - accuracy: 0.9869 - loss: 0.0745
Epoch 25/100
24/24 - 0s - 4ms/step - accuracy: 0.9883 - loss: 0.0665
Epoch 26/100
24/24 - 0s - 4ms/step - accuracy: 0.9896 - loss: 0.0603
Epoch 27/100
24/24 - 0s - 4ms/step - accuracy: 0.9896 - loss: 0.0549
Epoch 28/100
24/24 - 0s - 4ms/step - accuracy: 0.9909 - loss: 0.0500
Epoch 29/100
24/24 - 0s - 4ms/step - accuracy: 0.9909 - loss: 0.0459
Epoch 30/100
24/24 - 0s - 4ms/step - accuracy: 0.9909 - loss: 0.0425
Epoch 31/100
24/24 - 0s - 5ms/step - accuracy: 0.9909 - loss: 0.0393
Epoch 32/100
24/24 - 0s - 4ms/step - accuracy: 0.9909 - loss: 0.0364
Epoch 33/100
24/24 - 0s - 4ms/step - accuracy: 0.9909 - loss: 0.0336
Epoch 34/100
24/24 - 0s - 4ms/step - accuracy: 0.9922 - loss: 0.0312
Epoch 35/100
24/24 - 0s - 4ms/step - accuracy: 0.9935 - loss: 0.0290
Epoch 36/100
24/24 - 0s - 4ms/step - accuracy: 0.9935 - loss: 0.0269
Epoch 37/100
24/24 - 0s - 4ms/step - accuracy: 0.9961 - loss: 0.0250
Epoch 38/100
24/24 - 0s - 4ms/step - accuracy: 0.9974 - loss: 0.0234
Epoch 39/100
24/24 - 0s - 4ms/step - accuracy: 0.9987 - loss: 0.0219
Epoch 40/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0205
Epoch 41/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0193
Epoch 42/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0181
Epoch 43/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0170
Epoch 44/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0160
Epoch 45/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0151
Epoch 46/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0143
Epoch 47/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0135
Epoch 48/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0127
Epoch 49/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0121
Epoch 50/100
24/24 - 0s - 5ms/step - accuracy: 1.0000 - loss: 0.0114
Epoch 51/100
24/24 - 0s - 5ms/step - accuracy: 1.0000 - loss: 0.0109
Epoch 52/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0103
Epoch 53/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0099
Epoch 54/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0094
Epoch 55/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0090
Epoch 56/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0085
Epoch 57/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0082
Epoch 58/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0078
Epoch 59/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0074
Epoch 60/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0071
Epoch 61/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0068
Epoch 62/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0065
Epoch 63/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0063
Epoch 64/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0060
Epoch 65/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0058
Epoch 66/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0056
Epoch 67/100
24/24 - 0s - 7ms/step - accuracy: 1.0000 - loss: 0.0053
Epoch 68/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0051
Epoch 69/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0050
Epoch 70/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0047
Epoch 71/100
24/24 - 0s - 5ms/step - accuracy: 1.0000 - loss: 0.0046
Epoch 72/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0044
Epoch 73/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0043
Epoch 74/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0041
Epoch 75/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0040
Epoch 76/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0038
Epoch 77/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0037
Epoch 78/100
24/24 - 0s - 10ms/step - accuracy: 1.0000 - loss: 0.0036
Epoch 79/100
24/24 - 0s - 5ms/step - accuracy: 1.0000 - loss: 0.0035
Epoch 80/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0033
Epoch 81/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0032
Epoch 82/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0031
Epoch 83/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0030
Epoch 84/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0029
Epoch 85/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0028
Epoch 86/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0028
Epoch 87/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0027
Epoch 88/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0026
Epoch 89/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0025
Epoch 90/100
24/24 - 0s - 5ms/step - accuracy: 1.0000 - loss: 0.0024
Epoch 91/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0024
Epoch 92/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0023
Epoch 93/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0022
Epoch 94/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0022
Epoch 95/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0021
Epoch 96/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 97/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0020
Epoch 98/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0019
Epoch 99/100
24/24 - 0s - 5ms/step - accuracy: 1.0000 - loss: 0.0019
Epoch 100/100
24/24 - 0s - 4ms/step - accuracy: 1.0000 - loss: 0.0018
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

,TL_o,TL_x,TM_o,TM_x,TR_o,TR_x,ML_o,ML_x,MM_o,MM_x,MR_o,MR_x,BL_o,BL_x,BM_o,BM_x,BR_o,BR_x
836,True,False,True,False,True,False,False,False,False,True,False,True,False,True,True,False,False,True
477,True,False,False,False,False,False,False,True,False,True,False,True,False,False,False,False,True,False
350,True,False,False,True,False,False,False,True,False,True,False,False,True,False,False,True,True,False
891,False,False,False,True,True,False,False,True,False,True,True,False,False,True,True,False,True,False
855,True,False,False,False,False,True,False,True,True,False,False,False,False,False,False,True,True,False

[0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1
 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 1
 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0
 1 1 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1
 1 1 1 0 1 1 0]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# your code here

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here